### ISSUE TITLE
Docker Version?

### ISSUE THREAD

**Issue by ItsNoted** [The-Best-Codes/codequill#5]
Any plans to Dockerize the app? Also, are there any screenshots?

Thanks!

**Comment by The-Best-Codes** [comment]
@ItsNoted I just checked. The install file (https://github.com/The-Best-Codes/codequill/blob/main/codequill_app.sh) is working fine. When you start the app, a screen appears that says 'Loading CodeQuill'. After CodeQuill is loaded, the screen does not go away. :thinking: I need to fix that.

Otherwise, everything is working perfectly!

Also, a note: remember that wherever you download CodeQuill first, that is where the server and database will run. The other devices you download CodeQuill on will automatically detect CodeQuill running on that device to sync your codes across devices. So, run CodeQuill on a stable device first.

**Comment by The-Best-Codes** [comment]
I've added experimental docker support. Open an issue if you have any trouble with it.
